echo "TESTGEN: mem = 0"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {}"
echo "TESTGEN: cpu = 0"
kubectl delete pods rgu0 rbu0 rbe0 -n kube-system --now & kubectl delete pods --all --now || true; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 0"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {}"
echo "TESTGEN: cpu = 0"
NAME=gu0 CONTCOUNT=1 CPU=200m MEM=1500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 1500"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 200"
NAME=gu1 CONTCOUNT=2 CPU=1000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2500"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 2200"
NAME=gu3 CONTCOUNT=3 CPU=2000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4000"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 8200"
NAME=gu4 CONTCOUNT=1 CPU=5200m MEM=100M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4100"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 13400"
NAME=bu0 CONTCOUNT=1 CPU=900m MEM=50M CPUREQ=900m MEMREQ=50M CPULIM=1200m MEMLIM=100M create burstable; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be0 CONTCOUNT=1 CPU=0 MEM=0 create besteffort; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be1 CONTCOUNT=3 CPU=0 MEM=0 create besteffort; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu3 vm-command 'pkill -KILL -f echo\ gu3'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu4 vm-command 'pkill -KILL -f echo\ gu4c'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=bu0 vm-command 'pkill -KILL -f echo\ bu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be0 vm-command 'pkill -KILL -f echo\ be0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be1 vm-command 'pkill -KILL -f echo\ be0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 kubectl delete pod gu0 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14100"
NAME=gu1 kubectl delete pod gu1 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 1650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 12100"
NAME=gu3 kubectl delete pod gu3 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 6100"
NAME=bu1 CONTCOUNT=2 CPU=1900m MEM=50M CPUREQ=1900m MEMREQ=50M CPULIM=4000m MEMLIM=1000M create burstable; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 250"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'bu1': {CONTCOUNT:2,CPU:1900,CPULIM:4000,CPUREQ:1900,MEM:50,MEMLIM:1000,MEMREQ:50,NAME:bu1,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 9900"
NAME=bu1 vm-command 'pkill -KILL -f echo\ bu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 250"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu1': {CONTCOUNT:2,CPU:1900,CPULIM:4000,CPUREQ:1900,MEM:50,MEMLIM:1000,MEMREQ:50,NAME:bu1,namespace:default}"
echo "TESTGEN:   'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 9900"
NAME=gu4 kubectl delete pod gu4 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'bu1': {CONTCOUNT:2,CPU:1900,CPULIM:4000,CPUREQ:1900,MEM:50,MEMLIM:1000,MEMREQ:50,NAME:bu1,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 4700"
NAME=bu0 kubectl delete pod bu0 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 100"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu1': {CONTCOUNT:2,CPU:1900,CPULIM:4000,CPUREQ:1900,MEM:50,MEMLIM:1000,MEMREQ:50,NAME:bu1,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 3800"
NAME=bu1 kubectl delete pod bu1 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 0"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rgu0 CONTCOUNT=2 CPU=200m MEM=1000M namespace=kube-system create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2000"
echo "TESTGEN: reserved_cpu = 400"
echo "TESTGEN: pods = {'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rbu0 CONTCOUNT=1 CPU=200m MEM=100M CPUREQ=200m MEMREQ=100M CPULIM=2500m MEMLIM=2500M namespace=kube-system create burstable; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2100"
echo "TESTGEN: reserved_cpu = 600"
echo "TESTGEN: pods = {'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN:   'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rbe0 CONTCOUNT=2 CPU=0 MEM=0 namespace=kube-system create besteffort; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2100"
echo "TESTGEN: reserved_cpu = 600"
echo "TESTGEN: pods = {'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN:   'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rgu0 vm-command 'pkill -KILL -f echo\ rgu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2100"
echo "TESTGEN: reserved_cpu = 600"
echo "TESTGEN: pods = {'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN:   'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rbu0 vm-command 'pkill -KILL -f echo\ rbu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2100"
echo "TESTGEN: reserved_cpu = 600"
echo "TESTGEN: pods = {'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN:   'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rbe0 vm-command 'pkill -KILL -f echo\ rbe0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2100"
echo "TESTGEN: reserved_cpu = 600"
echo "TESTGEN: pods = {'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN:   'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=be0 kubectl delete pod be0 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2100"
echo "TESTGEN: reserved_cpu = 600"
echo "TESTGEN: pods = {'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN:   'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=be1 kubectl delete pod be1 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2100"
echo "TESTGEN: reserved_cpu = 600"
echo "TESTGEN: pods = {'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN:   'rgu0': {CONTCOUNT:2,CPU:200,MEM:1000,NAME:rgu0,namespace:kube-system}"
echo "TESTGEN:   'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rgu0 kubectl delete pod rgu0 -n kube-system --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 100"
echo "TESTGEN: reserved_cpu = 200"
echo "TESTGEN: pods = {'rbu0': {CONTCOUNT:1,CPU:200,CPULIM:2500,CPUREQ:200,MEM:100,MEMLIM:2500,MEMREQ:100,NAME:rbu0,namespace:kube-system}"
echo "TESTGEN:   'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rbu0 kubectl delete pod rbu0 -n kube-system --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 0"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'rbe0': {CONTCOUNT:2,CPU:0,MEM:0,NAME:rbe0,namespace:kube-system}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 0"
NAME=rbe0 kubectl delete pod rbe0 -n kube-system --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 0"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {}"
echo "TESTGEN: cpu = 0"
kubectl delete pods rgu0 rbu0 rbe0 -n kube-system --now & kubectl delete pods --all --now || true; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 0"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {}"
echo "TESTGEN: cpu = 0"
NAME=gu0 CONTCOUNT=1 CPU=200m MEM=1500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 1500"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 200"
NAME=gu3 CONTCOUNT=3 CPU=2000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 3000"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 6200"
NAME=gu1 CONTCOUNT=2 CPU=1000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4000"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 8200"
NAME=gu4 CONTCOUNT=1 CPU=5200m MEM=100M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4100"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 13400"
NAME=be0 CONTCOUNT=1 CPU=0 MEM=0 create besteffort; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4100"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 13400"
NAME=bu0 CONTCOUNT=1 CPU=900m MEM=50M CPUREQ=900m MEMREQ=50M CPULIM=1200m MEMLIM=100M create burstable; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be1 CONTCOUNT=3 CPU=0 MEM=0 create besteffort; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu3 vm-command 'pkill -KILL -f echo\ gu3'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu4 vm-command 'pkill -KILL -f echo\ gu4c'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=bu0 vm-command 'pkill -KILL -f echo\ bu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be0 vm-command 'pkill -KILL -f echo\ be0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be1 vm-command 'pkill -KILL -f echo\ be0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 kubectl delete pod gu0 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14100"
NAME=gu0 CONTCOUNT=1 CPU=200m MEM=1500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 kubectl delete pod gu1 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 3150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 12300"
NAME=gu1 CONTCOUNT=2 CPU=1000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu3 kubectl delete pod gu3 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 8300"
NAME=gu3 CONTCOUNT=3 CPU=2000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu4 kubectl delete pod gu4 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4050"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 9100"
NAME=gu4 CONTCOUNT=1 CPU=5200m MEM=100M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=bu0 kubectl delete pod bu0 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4100"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 13400"
NAME=bu0 CONTCOUNT=1 CPU=900m MEM=50M CPUREQ=900m MEMREQ=50M CPULIM=1200m MEMLIM=100M create burstable; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be0 kubectl delete pod be0 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be0 CONTCOUNT=1 CPU=0 MEM=0 create besteffort; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be1 kubectl delete pod be1 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be1 CONTCOUNT=3 CPU=0 MEM=0 create besteffort; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu3 vm-command 'pkill -KILL -f echo\ gu3'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu4 vm-command 'pkill -KILL -f echo\ gu4c'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=bu0 vm-command 'pkill -KILL -f echo\ bu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be0 vm-command 'pkill -KILL -f echo\ be0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=be1 vm-command 'pkill -KILL -f echo\ be0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu0 kubectl delete pod gu0 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14100"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14100"
NAME=gu0 CONTCOUNT=1 CPU=200m MEM=1500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 kubectl delete pod gu1 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 3150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 12300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 3150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 12300"
NAME=gu1 CONTCOUNT=2 CPU=1000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu3 kubectl delete pod gu3 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 8300"
NAME=gu0 vm-command 'pkill -KILL -f echo\ gu0c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 2650"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 8300"
NAME=gu3 CONTCOUNT=3 CPU=2000m MEM=500M create guaranteed; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu1 vm-command 'pkill -KILL -f echo\ gu1c0'; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4150"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'gu4': {CONTCOUNT:1,CPU:5200,MEM:100,NAME:gu4,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 14300"
NAME=gu4 kubectl delete pod gu4 --now; kubectl get pods -A; vm-command "date +%T.%N"
echo "TESTGEN: mem = 4050"
echo "TESTGEN: reserved_cpu = 0"
echo "TESTGEN: pods = {'bu0': {CONTCOUNT:1,CPU:900,CPULIM:1200,CPUREQ:900,MEM:50,MEMLIM:100,MEMREQ:50,NAME:bu0,namespace:default}"
echo "TESTGEN:   'gu3': {CONTCOUNT:3,CPU:2000,MEM:500,NAME:gu3,namespace:default}"
echo "TESTGEN:   'gu1': {CONTCOUNT:2,CPU:1000,MEM:500,NAME:gu1,namespace:default}"
echo "TESTGEN:   'gu0': {CONTCOUNT:1,CPU:200,MEM:1500,NAME:gu0,namespace:default}"
echo "TESTGEN:   'be0': {CONTCOUNT:1,CPU:0,MEM:0,NAME:be0,namespace:default}"
echo "TESTGEN:   'be1': {CONTCOUNT:3,CPU:0,MEM:0,NAME:be1,namespace:default}"
echo "TESTGEN: }"
echo "TESTGEN: cpu = 9100"
NAME=bu1 CONTCOUNT=2 CPU=1900m MEM=50M CPUREQ=1900m MEMREQ=50M CPULIM=4000m MEMLIM=1000M create burstable; kubectl get pods -A; vm-command "date +%T.%N"
