name: Release Tests
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Protoc
      run: go get -u github.com/golang/protobuf/protoc-gen-go

    - name: Protoc-gRPC
      run: go get -u google.golang.org/grpc

    - name: InstallVFSGenDev
      run: go get -u github.com/shurcooL/vfsgen/cmd/vfsgendev

    - name: Release Tests
      env:
        GITHUB_BASE_REF: ${{ github.base_ref }}
      run: |
        case $GITHUB_BASE_REF in
        release*)
            echo "Insalling/building govm and its dependencies..."
            sudo apt-get -y install qemu-system-x86
            git clone https://github.com/govm-project
            cd govm-project
            go build -o govm && cp govm $GOPATH/bin
            sudo docker build . -f Dockerfile -t govm/govm:latest
            cd ..
            ;;
        esac

    - name: Release Tests
      env:
        GITHUB_BASE_REF: ${{ github.base_ref }}
      run: |
        case $GITHUB_BASE_REF in
        release*)
            make release-tests
            ;;
        default)
            echo "Skipping relese test for non-release branch $GITHUB_BASE_REF"
        esac
